-- ==============================================================================
-- SUPERMANAGER PRO: Import Paint & Hardware Shop Catalog (528 Products)
-- Target Account: bahriahmedwalid@gmail.com (with universal auth user resolution)
-- ==============================================================================

-- 1. Ensure store profile exists for the user
INSERT INTO public.store_profiles (owner_id, name, category, currency)
SELECT u.id, 'Magasin Peinture & Droguerie', 'peinture_droguerie', 'DA'
FROM (
  SELECT id FROM auth.users WHERE LOWER(email) = LOWER('bahriahmedwalid@gmail.com')
  UNION
  SELECT id FROM auth.users LIMIT 1
) u
LIMIT 1;

-- 2. Insert all 528 products
INSERT INTO public.products (owner_id, sku, name, price, wholesale_price, special_price, stock, min_stock, category)
SELECT 
  u.id, 
  v.sku, 
  v.name, 
  v.price, 
  v.wholesale_price, 
  v.special_price, 
  v.stock, 
  v.min_stock, 
  v.category
FROM (
  SELECT id FROM auth.users WHERE LOWER(email) = LOWER('bahriahmedwalid@gmail.com')
  UNION
  SELECT id FROM auth.users LIMIT 1
) u
CROSS JOIN (VALUES
  ('CT44150', 'NIVEAU LASER CROWN CT44150 30M (نيفو ليزر كراون 30 متر)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('CT44091', 'NIVEAU LASER CROWN CT44091 16 LIGNES 30M (نيفو ليزر كراون 16 خط 30 متر)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('NLR-16', 'NIVEAU LASER FIX TOPE 16 LIGNES (نيفو ليزر فيكس طوب 16 خط)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('CHEV-M6', 'CHEVILLE METALLIQUE M6 (شوفي ميتاليك 6)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('CHEV-M8', 'CHEVILLE METALLIQUE M8 (شوفي ميتاليك 8)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('18386', 'SPOT SAMSUNG 10W 3D (سبوت سامسونغ 10 واط 3 دي)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('LMPW11W', 'LAMPE 11W LED WELLMAX (لامبة 11 واط ليد ويلماكس)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('13314', 'LAMPE 13W WELLMAX (لامبة 13 واط ويلماكس)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('TIG-F06', 'TIGE FILETEE N°06 (تيج فيلتي رقم 6)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('TIG-F08', 'TIGE FILETEE N°08 (تيج فيلتي رقم 8)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('5406', 'LA FARGE PATE A JOINT BLANC 5KG (لافارج باط أ جوان أبيض 5 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('9320', 'MIDY LAQUE BLEU CIEL 700G (ميدي لاك أزرق سماوي 700 غ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('9321', 'MIDY LAQUE JAUNE 700G (ميدي لاك أصفر 700 غ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('PRO-SIL-TR', 'COLLE SILICONE PROSEAL NACISIL TRANSPARENT (كول سيليكون بروسيل ترونسبارو)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Droguerie & Mastics'),
  ('PRO-SIL-BL', 'COLLE SILICONE PROSEAL NACISIL BLANC (كول سيليكون بروسيل أبيض)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Droguerie & Mastics'),
  ('SASKPS', 'SOUKOY SKY PRISE SIMPLE (سوكوي سكاي بريز سامبل)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('SASKSA', 'SOUKOY SKY INTERRUPTEUR SIMPLE (سوكوي سكاي أنتربتور سامبل)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('SASKVV', 'SOUKOY SKY INTERRUPTEUR VA ET VIENT (سوكوي سكاي فافيانت)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('GOUL-1212', 'GOULOTTE PVC 12X12 (قولوط بلاستيك 12/12)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('GOUL-1616', 'GOULOTTE PVC 16X16 (قولوط بلاستيك 16/16)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('GOUL-2516', 'GOULOTTE PVC 25X16 (قولوط بلاستيك 25/16)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('GOUL-4025', 'GOULOTTE PVC 40X25 (قولوط بلاستيك 40/25)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('GRL-AER-10', 'GRILLE D''AERATION 10X10 (قري دايراسيون 10/10)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('GRL-AER-15', 'GRILLE D''AERATION 15X15 (قري دايراسيون 15/15)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('DOUILLE-E27', 'DOUILLE E27 A VIS (دوي أ فيس 27)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('TR-MIM-210-BL', 'TRINGLE MIMOZA 2.10M BLANC (ترانغل ميموزا 2.10م أبيض)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('TR-MIM-210-NR', 'TRINGLE MIMOZA 2.10M NOIR (ترانغل ميموزا 2.10م أسود)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('TR-MIM-210-BZ', 'TRINGLE MIMOZA 2.10M BRONZE (ترانغل ميموزا 2.10م برونز)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('CAB-2X25-ELW', 'CABLE SOUPLE 2X2.5 EL WAFAA (كابل سوبل 2*2.5 الوفاء)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('BOUL-820', 'BOULON 8X20 AVEC ECROU (بولون 8*20 مع لكرو)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('FIL-15-MOSTA', 'FIL ELECTRIQUE 1.5 MOSTA (خيط تريسيتي 1.5 مستغانم)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('FIL-25-MOSTA', 'FIL ELECTRIQUE 2.5 MOSTA (خيط تريسيتي 2.5 مستغانم)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('CAB-2X6-SETIF', 'CABLE 2X6 SETIF (كابل تريسيتي 2*6 سطيف)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('ECROU-N05', 'ECROU N°05 (إكرو رقم 5)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('ECROU-N06', 'ECROU N°06 (إكرو رقم 6)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('ECROU-N08', 'ECROU N°08 (إكرو رقم 8)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('SM23-120', 'SERRURE SMTOP SM23 120 (قفل سيرير أس أم طوب 120)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('SM27-CS', 'SERRURE SMTOP SM27 C/S (قفل سيرير أس أم طوب 27)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('LMP-SAMS-9W-REC', 'LAMPE RECHARGEABLE SAMSUNG 9W (لامبة روشارجابل سامسونغ 9 واط)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('LMP-SAMS-11W-REC', 'LAMPE RECHARGEABLE SAMSUNG 11W (لامبة روشارجابل سامسونغ 11 واط)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('LMP-SAMS-13W-REC', 'LAMPE RECHARGEABLE SAMSUNG 13W (لامبة روشارجابل سامسونغ 13 واط)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('LMP-SAMS-18W-REC', 'LAMPE RECHARGEABLE SAMSUNG 18W (لامبة روشارجابل سامسونغ 18 واط)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('21029', 'MOUSSE SELSIL 750ML (موس سيلسيل 750 مل)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Droguerie & Mastics'),
  ('TELERUP-CHINT-16A', 'TELERUPTEUR CHINT 16A (تيليريبتور شانت 16 أمبير)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('GLUE-FASTWELD', 'COLLE SUPER GLUE + DURCISSEUR FAST WELD (سوبر قلو مع دورسيسور فاست ويلد)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Droguerie & Mastics'),
  ('ESCAB-EULMA-N6', 'ESCABEAU EULMA N°6 (سلم ألمنيوم العلمة 6 درجات)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('ESCAB-EULMA-N7', 'ESCABEAU EULMA N°7 (سلم ألمنيوم العلمة 7 درجات)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('TR-DBL-210-CH', 'TRINGLE DOUBLE 2.10M CHROME (ترانغل دوبل 2.10م كرومي)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('TR-DBL-210-BZ', 'TRINGLE DOUBLE 2.10M BRONZE (ترانغل دوبل 2.10م برونز)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('18027', 'SPOT SAMSUNG 36W 3D (سبوت سامسونغ 36 واط)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('18385', 'SPOT SAMSUNG 18W 3D (سبوت سامسونغ 18 واط)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('DISQ-RES-220', 'DISQUE RESINE SCRATCH N°220 (ديسك ريزين سكراش 220)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('PLAQ-KNAUF-BA13', 'PLAQUE KNAUF BA13 STANDARD (بلاكة كناوف بلاكو با13)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('PLAQ-HYDRO-BA13', 'PLAQUE KNAUF HYDROFUGE BA13 VERT (بلاكة كناوف هيدروفوج خضراء با13)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('CORN-GALVA', 'CORNIERE GALVA 3M (كورنيير قالفا 3م)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('FOUR-3M', 'FOURRURE 3M (فورير 3م)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('FOUR-4M', 'FOURRURE 4M (فورير 4م)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('FOUR-53M', 'FOURRURE 5.3M (فورير 5.3م)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('RAIL-48', 'RAIL 48 GALVA (راي 48 قالفا)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('MONT-48', 'MONTANT 48 GALVA (مونطو 48 قالفا)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('RAIL-70', 'RAIL 70 GALVA (راي 70 قالفا)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('MONT-70', 'MONTANT 70 GALVA (مونطو 70 قالفا)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('TIGE-MAHOR', 'TIGE MAHOR POUR SUSPENTE (تيج ماهور سوسبونت)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('VIS-25-ABC', 'VIS PLACO 25 ABC (فيس بلاكو 25 أ ب س)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('CAVALIER-SURIN', 'CAVALIER SURIN POUR FOURRURE (كافالي سوران)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('CHEVILLE-LITON', 'CHEVILLE LAITON POUR PLACO (شوفي ليتون نحاس)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('CHEVILLE-FRAPPE', 'CHEVILLE A FRAPPER (شوفي أ فرابي)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('ENDUIT-TERRACO-25KG', 'ENDUIT TERRACO 25KG (لاندوي تيراكو 25 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('PERLFIX-KNAUF', 'PERLFIX KNAUF COLLE PLACO 25KG (بيرلفيكس كناوف كول بلاكو 25 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('PLACOL-COLLE', 'PLACOL COLLE POUR PLACO 25KG (بلاكول كول بلاكو 25 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('BANDE-ARMEE', 'BANDE ARMEE POUR PLACO (بوند أرمي بلاكو)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('BANDE-ADHESIVE', 'BANDE ADHESIVE GRILLAGE (بوند أدريزيف قرياج)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('BANDE-A-JOINT', 'BANDE A JOINT PAPIER KNAUF (بوند أ جوان كناوف)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('GORGE-PVC-H4', 'GORGE PVC H4 (غورج بلاستيك أش 4)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('PLAQ-CHEVAL-BLANC', 'PLAQUE CHEVAL BLANC BA13 (بلاكة شوفال بلون با13)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('PROF-OMG', 'PROFILS OMG ALU (بروفيل أ و أم جي)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('PVC-MAHOR-B5', 'PVC MAHOR B5 (بي في سي ماهور ب5)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Placo & Décoration PVC'),
  ('PVC-MAHOR-W17', 'PVC MAHOR W17 (بي في سي ماهور دبل يو 17)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Placo & Décoration PVC'),
  ('PVC-MAHOR-S10', 'PVC MAHOR S10 (بي في سي ماهور أس 10)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Placo & Décoration PVC'),
  ('PVC-MAHOR-S1B', 'PVC MAHOR S1B (بي في سي ماهور أس 1 ب)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Placo & Décoration PVC'),
  ('PVC-MAHOR-E3', 'PVC MAHOR E3 (بي في سي ماهور أو 3)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Placo & Décoration PVC'),
  ('PVC-MAHOR-S11', 'PVC MAHOR S11 (بي في سي ماهور أس 11)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Placo & Décoration PVC'),
  ('PVC-SINDA-G13', 'PVC SINDA G13 (بي في سي سيندا جي 13)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Placo & Décoration PVC'),
  ('PVC-SINDA-G15', 'PVC SINDA G15 (بي في سي سيندا جي 15)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Placo & Décoration PVC'),
  ('PVC-SINDA-G74', 'PVC SINDA G7-4 (بي في سي سيندا جي 7-4)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Placo & Décoration PVC'),
  ('PVC-SINDA-E15', 'PVC SINDA E15 (بي في سي سيندا أو 15)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Placo & Décoration PVC'),
  ('PVC-SINDA-AD3002', 'PVC SINDA ADIDAS 3002 (بي في سي سيندا أديداس 3002)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Placo & Décoration PVC'),
  ('PVC-SINDA-1002', 'PVC SINDA 1002 (بي في سي سيندا 1002)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Placo & Décoration PVC'),
  ('WPC-BEIGE', 'PANNEAU WPC DECORATIF BEIGE (بانو دوبل في بي سي بيج)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Placo & Décoration PVC'),
  ('WPC-BLANC-MARBRE', 'PANNEAU WPC BLANC MARBRE (بانو دوبل في بي سي رخام أبيض)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Placo & Décoration PVC'),
  ('WPC-MARRON-CLAIR', 'PANNEAU WPC MARRON CLAIR (بانو دوبل في بي سي بني فاتح)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Placo & Décoration PVC'),
  ('WPC-CHOCO', 'PANNEAU WPC CHOCO MEUBLE (بانو دوبل في بي سي شوكولا)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Placo & Décoration PVC'),
  ('WPC-GRIS', 'PANNEAU WPC GRIS (بانو دوبل في بي سي رمادي)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Placo & Décoration PVC'),
  ('WPC-FAUX-BOIS', 'PANNEAU WPC FAUX BOIS (بانو دوبل في بي سي خشب)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Placo & Décoration PVC'),
  ('WPC-NOIR-DORE', 'PANNEAU WPC NOIR DORE (بانو دوبل في بي سي أسود ذهبي)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Placo & Décoration PVC'),
  ('MARB-F130', 'FAUX MARBRE ROULEAU F-130 (فو ماربر رولو 130)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Placo & Décoration PVC'),
  ('MARB-F131', 'FAUX MARBRE ROULEAU F-131 (فو ماربر رولو 131)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Placo & Décoration PVC'),
  ('MARB-F153', 'FAUX MARBRE ROULEAU F-153 (فو ماربر رولو 153)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Placo & Décoration PVC'),
  ('MARB-F24', 'FAUX MARBRE ROULEAU F-24 (فو ماربر رولو 24)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Placo & Décoration PVC'),
  ('MARB-F27', 'FAUX MARBRE ROULEAU F-27 (فو ماربر رولو 27)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Placo & Décoration PVC'),
  ('GAZON-SYNTH', 'GAZON SYNTHETIQUE ROULEAU (قازون اصطناعي رولو)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Placo & Décoration PVC'),
  ('5108', 'PANDA RACLETTE ROND N18 PLASTIC (باندا راكليط مدور بلاستيك 18)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('GHDOJD', 'PANDA RACLETTE ROND N20 PLASTIC (باندا راكليط مدور بلاستيك 20)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('+*1', 'PANDA RACLETTE ROND N22 PLASTIC (باندا راكليط مدور بلاستيك 22)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('8536', 'PANDA RACLETTE ROND N24 PLASTIQUE (باندا راكليط مدور بلاستيك 24)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('5120', 'LEADER RACLETTE ROND PLAST N°22 (راكليط ليدر مدور بلاستيك 22)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('5121', 'LEADER RACLETTE ROND PLAST N°24 (راكليط ليدر مدور بلاستيك 24)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('RAC-LEAD-10', 'RACLETTE LEADER INOX 10CM (راكليط إينوكس ليدر 10 سم)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('RAC-LEAD-12', 'RACLETTE LEADER INOX 12CM (راكليط إينوكس ليدر 12 سم)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('RAC-LEAD-14', 'RACLETTE LEADER INOX 14CM (راكليط إينوكس ليدر 14 سم)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('RAC-LEAD-16', 'RACLETTE LEADER INOX 16CM (راكليط إينوكس ليدر 16 سم)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('RAC-LEAD-24', 'RACLETTE LEADER INOX 24CM (راكليط إينوكس ليدر 24 سم)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('SEAU-25L', 'SEAU PLASTIQUE GRADUE 2.5L (دلو بلاستيك 2.5 لتر)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('SEAU-32L', 'SEAU PLASTIQUE GRADUE 3.2L (دلو بلاستيك 3.2 لتر)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('SEAU-38L', 'SEAU PLASTIQUE GRADUE 3.8L (دلو بلاستيك 3.8 لتر)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('SEAU-5L', 'SEAU PLASTIQUE GRADUE 5L (دلو بلاستيك 5 لتر)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('LISS-DEC-2610', 'LISSEUSE DECORATIVE INOX 26X10 (ليسوز ديكور إينوكس 26*10)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('LISS-DEC-2410', 'LISSEUSE DECORATIVE INOX 24X10 (ليسوز ديكور إينوكس 24*10)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('LISS-DEC-2008', 'LISSEUSE DECORATIVE INOX 20X8 (ليسوز ديكور إينوكس 20*8)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('PLAT-SCR-150', 'PLATEAU SCRATCH AUTO-AGRIPPANT 150MM (بلاطو سكراش 150)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('PLAT-SCR-180', 'PLATEAU SCRATCH AUTO-AGRIPPANT 180MM (بلاطو سكراش 180)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('MEGA-ET-5KG-BL', 'MEGA ETANCHE 5KG BLANC (ميغا إيتونش 5 كغ أبيض)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('MEGA-ET-10KG-BL', 'MEGA ETANCHE 10KG BLANC (ميغا إيتونش 10 كغ أبيض)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('MEGA-ET-20KG-BL', 'MEGA ETANCHE 20KG BLANC (ميغا إيتونش 20 كغ أبيض)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('MEGA-ET-20KG-GR', 'MEGA ETANCHE 20KG GRIS (ميغا إيتونش 20 كغ رمادي)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('MEGA-ET-20KG-RG', 'MEGA ETANCHE 20KG ROUGE TUILE (ميغا إيتونش 20 كغ أحمر قرمودي)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('VALP-VALSETIN', 'VALPAINT VALSETIN PEINTURE DECORATIVE (فالبانت فالستين ديكور)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('3242', 'VALPAINT STUCCO 1000 5KG (فالبانت ستيكو 1000 5 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('VALP-ARTECO', 'VALPAINT ARTECO 7 EFFET VIEILLI (فالبانت أرتيكو 7)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('VALP-P40', 'VALPAINT METEORE 8 P40 (فالبانت ميتيور ب40)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('VALP-TRAVERTINO', 'VALPAINT TRAVERTINO DECOR (فالبانت ترافيرتينو رخام)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('10020', 'SNIC LAQUE BLANCHE 3KG (سنيك لاك أبيض 3 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('SNIC-LAQ-25KG', 'SNIC LAQUE BRILLANTE 2.5KG (سنيك لاك لامع 2.5 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('GLIT-ARG-100', 'PAILLETTES GLITTER ARGENT 100G (باييت جليتر فضي 100غ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('GLIT-OR-100', 'PAILLETTES GLITTER OR 100G (باييت جليتر ذهبي 100غ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('DEG-GRIGRI', 'DEGRIPPANT MULTI-USAGES GRI-GRI (ديقريبون قري قري)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Droguerie & Mastics'),
  ('SIL-SOFITEX-BL', 'COLLE SILICONE SOFITEX BLANC (كول سيليكون سوفيتكس أبيض)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Droguerie & Mastics'),
  ('SIL-SOFITEX-TR', 'COLLE SILICONE SOFITEX TRANSPARENT (كول سيليكون سوفيتكس ترونسبارو)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Droguerie & Mastics'),
  ('SIACOL-400G', 'ESSAADA SIACOL COLLE BLANCHE BOIS 400G (السعادة سياكول خشب 400 غ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Droguerie & Mastics'),
  ('SIACOL-800G', 'ESSAADA SIACOL COLLE BLANCHE BOIS 800G (السعادة سياكول خشب 800 غ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Droguerie & Mastics'),
  ('SIACOL-3KG', 'ESSAADA SIACOL COLLE BLANCHE BOIS 3KG (السعادة سياكول خشب 3 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Droguerie & Mastics'),
  ('COLLE-PVC-125', 'COLLE TUBE PVC RIGIDE 125ML (كول بي في سي 125 مل)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Droguerie & Mastics'),
  ('COLLE-PVC-250', 'COLLE POT PVC AVEC PINCEAU 250ML (كول بي في سي مع بانسو 250 مل)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Droguerie & Mastics'),
  ('1321', 'MEGA SATINEE 4KG 1321 CHOCOLAT (ميغا ساتيني 4 كغ شوكولا)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('1328', 'MEGA SATINEE 4KG 1328 MAUVE (ميغا ساتيني 4 كغ موف)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('1429', 'MEGA SATINEE 4KG 1429 CREVETTE (ميغا ساتيني 4 كغ كريفات)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('1631', 'MEGA SATINEE 4KG 1634 ROUGE BRIQUE (ميغا ساتيني 4 كغ أحمر بريك)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('1680', 'MEGA SATINEE 4KG 1680 CASSIS (ميغا ساتيني 4 كغ كاسيس)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('1696', 'MEGA SATINEE 4KG 1696 GRIS FONCE (ميغا ساتيني 4 كغ رمادي غامق)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('1161', 'MEGA SATINEE 4KG 1724 GRIS CLAIR (ميغا ساتيني 4 كغ رمادي فاتح)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('1754', 'MEGA SATINEE 4KG 1754 ROSE CLAIR (ميغا ساتيني 4 كغ وردي فاتح)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('1832', 'MEGA SATINEE 4KG 1832 PECHE (ميغا ساتيني 4 كغ خوخي)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('1359', 'MEGA SATINEE 4KG 1849 ORANGE (ميغا ساتيني 4 كغ برتقالي)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('1891', 'MEGA SATINEE 4KG 1891 NOIR (ميغا ساتيني 4 كغ أسود)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('1984', 'MEGA SATINEE 4KG 1984 ROSE FONCE (ميغا ساتيني 4 كغ وردي غامق)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('DCR G', 'MEGA SATINEE 4KG 2317 CREME (ميغا ساتيني 4 كغ كريمي)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('2507', 'MEGA SATINEE 4KG 2507 NOISETTE (ميغا ساتيني 4 كغ نوازيت)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('2611', 'MEGA SATINEE 4KG 2611 VERT GAZON (ميغا ساتيني 4 كغ أخضر قازون)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('2714', 'MEGA SATINEE 4KG 2714 FUCHSIA (ميغا ساتيني 4 كغ فوشيا)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('2521', 'MEGA SATINEE 4KG 2802 CAPPUCCINO (ميغا ساتيني 4 كغ كابوتشينو)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('10488', 'MEGA SATINEE 4KG 3144 BEIGE (ميغا ساتيني 4 كغ بيج)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('3823', 'MEGA SATINEE 4KG 3823 ROUGE VIF (ميغا ساتيني 4 كغ أحمر فاقع)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('4029', 'MEGA SATINEE 4KG 4029 BORDEAUX (ميغا ساتيني 4 كغ بوردو)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('4637', 'MEGA SATINEE 4KG 4637 PISTACHE (ميغا ساتيني 4 كغ بيستاش)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('4749', 'MEGA SATINEE 4KG 4749 SAUMON (ميغا ساتيني 4 كغ سومو)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('2230', 'MEGA SATINEE 4KG 2230 BLEU TURQUOISE (ميغا ساتيني 4 كغ أزرق تركواز)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('7879', 'MEGA SATINEE 4KG 746 VANILLA LATTE (ميغا ساتيني 4 كغ فانيلا لاتي)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('10399', 'MEGA SATINE BLANC 04KG (ميغا ساتيني أبيض 4 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('4775', 'ROLUX SCOTCH TOLIER BLANC GM (رولوكس سكوتش طوليا أبيض كبير)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Droguerie & Mastics'),
  ('4780', 'ROLUX SCOTCH TOLIER BLEU GM (رولوكس سكوتش طوليا أزرق كبير)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Droguerie & Mastics'),
  ('4772', 'ROLUX SCOTCH TOLIER JAUNE GM (رولوكس سكوتش طوليا أصفر كبير)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Droguerie & Mastics'),
  ('5884', 'SCOTCH TOLIER SPIDER BLEU GM (سكوتش طوليا سبايدر أزرق كبير)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Droguerie & Mastics'),
  ('SCOTCH-TR-50M', 'SCOTCH EMBALLAGE TRANSPARENT 50M (سكوتش شفاف 50م)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Droguerie & Mastics'),
  ('ROUL-MINI-LAQ', 'MINIROS ROULEAU LAQUE VELOURS (مينيروس رولو لاك)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('2656', 'PANDA ROULEAU ANTI GOUTTE GM (باندا رولو أونتي قوت كبير)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('4556', 'PANDA ROULEAU RAVALEMENT GM (باندا رولو رافالمان للواجهات كبير)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('5144', 'PANDA ROULEAU SATINE GM (باندا رولو ساتيني كبير)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('8541', 'PANDA ROULEAU SATINE 22CM (باندا رولو ساتيني 22 سم)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('PAND-P15', 'PANDA PINCEAU PLAT N°15 (باندا بانسو بلا رقم 15)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('PAND-P20', 'PANDA PINCEAU PLAT N°20 (باندا بانسو بلا رقم 20)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('PAND-P30', 'PANDA PINCEAU PLAT N°30 (باندا بانسو بلا رقم 30)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('PAND-P40', 'PANDA PINCEAU PLAT N°40 (باندا بانسو بلا رقم 40)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('PAND-P50', 'PANDA PINCEAU PLAT N°50 (باندا بانسو بلا رقم 50)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('PAND-P60', 'PANDA PINCEAU PLAT N°60 (باندا بانسو بلا رقم 60)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('PAND-P70', 'PANDA PINCEAU PLAT N°70 (باندا بانسو بلا رقم 70)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('PAND-P80', 'PANDA PINCEAU PLAT N°80 (باندا بانسو بلا رقم 80)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('PAND-R14', 'PANDA PINCEAU ROND N°14 (باندا بانسو مدور رقم 14)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('PAND-R18', 'PANDA PINCEAU ROND N°18 (باندا بانسو مدور رقم 18)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('PAND-R22', 'PANDA PINCEAU ROND N°22 (باندا بانسو مدور رقم 22)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('PAND-R26', 'PANDA PINCEAU ROND N°26 (باندا بانسو مدور رقم 26)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('BROSS-PAND-70', 'BROSSE DECORATIVE PANDA 70MM (شيتة ديكور باندا 70 مم)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('BROSS-PAND-100', 'BROSSE DECORATIVE PANDA 100MM (شيتة ديكور باندا 100 مم)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('2146', 'ESSENCE THERBENTINE 65CL (ليصونص التربنتين 65 سل)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Droguerie & Mastics'),
  ('HUILE-LIN-65', 'HUILE DE LIN PUR 65CL (زيت الكتان 65 سل)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Droguerie & Mastics'),
  ('HUILE-LIN-5L', 'HUILE DE LIN PUR 5L (زيت الكتان 5 لتر)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Droguerie & Mastics'),
  ('DILUANT-1L', 'DILUANT CELLULOSIQUE POLAR 1L (ديلوان بولار 1 لتر)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Droguerie & Mastics'),
  ('UNITAINT-MAG', 'UNITAINT TEINTURE UNIVERSELLE MAGENTA (يونيتانت صبغة ماجنتا)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('UNITAINT-JAU', 'UNITAINT TEINTURE UNIVERSELLE JAUNE (يونيتانت صبغة صفراء)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('UNITAINT-PIS', 'UNITAINT TEINTURE UNIVERSELLE PISTACHE (يونيتانت صبغة بيستاش)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('UNITAINT-CRM', 'UNITAINT TEINTURE UNIVERSELLE CREME (يونيتانت صبغة كريمي)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('UNITAINT-VRT', 'UNITAINT TEINTURE UNIVERSELLE VERT (يونيتانت صبغة خضراء)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('UNITAINT-ORG', 'UNITAINT TEINTURE UNIVERSELLE ORANGE (يونيتانت صبغة برتقالية)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('UNITAINT-BLU', 'UNITAINT TEINTURE UNIVERSELLE BLEU (يونيتانت صبغة زرقاء)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('UNITAINT-CAP', 'UNITAINT TEINTURE UNIVERSELLE CAPPUCCINO (يونيتانت صبغة كابوتشينو)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('5207', 'UNITAINT / UNIVERSEL TUBE IND NOIR (توب تانت أندستريال أسود)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('5209', 'UNITAINT / UNIVERSEL TUBE IND MARRON (توب تانت أندستريال بني)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('5213', 'UNITAINT / UNIVERSEL TUBE IND BEIGE (توب تانت أندستريال بيج)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('5226', 'UNITAINT / UNIVERSEL TUBE IND SAUMON (توب تانت أندستريال سومو)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('5848', 'PIGMA TUBE TEINTURE ORANGE (بيغما توب صبغة برتقالي)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('BOMB-GRIGRI-BL', 'BOMBE PEINTURE GRI-GRI BLANC BRILLANT (بومبة قري قري بيضاء لامعة)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('BOMB-GRIGRI-DOR', 'BOMBE PEINTURE GRI-GRI DOREE (بومبة قري قري ذهبي)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('BOMB-GRIGRI-ARG', 'BOMBE PEINTURE GRI-GRI ARGENTEE (بومبة قري قري فضي)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('BOMB-GRIGRI-GR', 'BOMBE PEINTURE GRI-GRI GRIS (بومبة قري قري رمادي)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('BOMB-GRIGRI-NRM', 'BOMBE PEINTURE GRI-GRI NOIR MAT (بومبة قري قري أسود ماط)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('BOMB-GRIGRI-NRB', 'BOMBE PEINTURE GRI-GRI NOIR BRILLANT (بومبة قري قري أسود بريون)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('BOMB-GRIGRI-RG', 'BOMBE PEINTURE GRI-GRI ROUGE (بومبة قري قري أحمر)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('BOMB-GRIGRI-VR', 'BOMBE PEINTURE GRI-GRI VERT (بومبة قري قري أخضر)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('BOMB-GRIGRI-CHR', 'BOMBE PEINTURE GRI-GRI EFFET CHROME (بومبة قري قري كروم)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('PAP-MANG-60', 'PAPIER DE VERRE MANGOUSTE GRAIN 60 (كارت قلاص منقوست حرش 60)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('PAP-MANG-80', 'PAPIER DE VERRE MANGOUSTE GRAIN 80 (كارت قلاص منقوست حرش 80)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('PAP-MANG-100', 'PAPIER DE VERRE MANGOUSTE GRAIN 100 (كارت قلاص منقوست متوسط 100)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('PAP-MANG-120', 'PAPIER DE VERRE MANGOUSTE GRAIN 120 (كارت قلاص منقوست متوسط 120)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('PAP-MANG-180', 'PAPIER DE VERRE MANGOUSTE GRAIN 180 (كارت قلاص منقوست رطب 180)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('PAP-MANG-220', 'PAPIER DE VERRE MANGOUSTE GRAIN 220 (كارت قلاص منقوست رطب 220)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('PAP-MANG-400', 'PAPIER DE VERRE MANGOUSTE GRAIN 400 A L''EAU (كارت قلاص منقوست ناعم 400)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('BANDE-DARK-40', 'BANDE ABRASIVE DARK GRAIN 40 (بوند أبغازيف دارك 40)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('BANDE-DARK-60', 'BANDE ABRASIVE DARK GRAIN 60 (بوند أبغازيف دارك 60)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('BANDE-DARK-80', 'BANDE ABRASIVE DARK GRAIN 80 (بوند أبغازيف دارك 80)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('9OI', 'SAIT EN ROULEAU ABRASIF N°150 (صايط رولو أبغازيف 150)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('2772', 'MIDY LAQUE NOIR 2.7KG (ميدي لاك أسود 2.7 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('2961', 'MIDY LAQUE GRIS 2.7KG (ميدي لاك رمادي 2.7 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('4230', 'MIDY LAQUE GRIS 700G (ميدي لاك رمادي 700 غ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('9777', 'MIDY LAQUE LC3 BLANC 700G (ميدي لاك إل سي 3 أبيض 700 غ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('10606', 'MIDY LAQUE LC3 BLANC 2.7KG (ميدي لاك إل سي 3 أبيض 2.7 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('810', 'ESSAADA ANTIROUILLE MARRON 800G (السعادة أونتي روي بني 800 غ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('EPL?D', 'ESSAADA ANTIROUILLE MARRON 2.7 KG (السعادة أونتي روي بني 2.7 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('2781', 'MIDY VERNIS ACAJOU 720G (ميدي فيرني أكاجو 720 غ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('118', 'MIDY VERNIS INCOLORE 800G (ميدي فيرني بدون لون 800 غ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('4710', 'MIDY VERNIS MARIN 2.700 KG (ميدي فيرني ماران بحري 2.7 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('10703', 'MEGA VERNIS DECORATIF 03KG (ميغا فيرني ديكوراتيف 3 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('5862', 'MANCHE TELESCOPIQUE PANDA 3M SL-T5540 (منش تيليسكوبيك باندا 3م)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('MANCH-PAND-2M', 'MANCHE TELESCOPIQUE PANDA 2M (منش تيليسكوبيك باندا 2م)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('LISS-GALAXY', 'LISSEUSE SPECIAL GALAXY SOUPLE (ليسوز ديكور قالاكسي)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('EPONGE-MARINE', 'EPONGE NATURELLE MARINE POUR DECOR (بونجة مارين للديكور)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('DISQ-GIRAF-60', 'DISQUE PONCEUSE GIRAFE MANULI 60 (ديسك بونسوز جيراف 60)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('DISQ-GIRAF-150', 'DISQUE PONCEUSE GIRAFE MANULI 150 (ديسك بونسوز جيراف 150)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('DISQ-GIRAF-180', 'DISQUE PONCEUSE GIRAFE MANULI 180 (ديسك بونسوز جيراف 180)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('DISQ-GIRAF-400', 'DISQUE PONCEUSE GIRAFE MANULI 400 (ديسك بونسوز جيراف 400)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('DISQ-MIRKA-4000', 'DISQUE ABRALON STUCCO MIRKA 4000 (ديسك ميركا ستيكو 4000)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('4302', 'MIDY BLANDEX 5KG (ميدي بلانديكس 5 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('4299', 'MIDY BLANDEX 10KG (ميدي بلانديكس 10 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('4300', 'MIDY BLANDEX 25KG (ميدي بلانديكس 25 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('160X10', 'BADI LAVABLE ECO 25KG PLASTIQUE (بادي لافابل إيكو 25 كغ بلاستيك)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('ZAKARIA', 'STAR LAVABLE ECOWALL 4KG (ستار لافابل إيكو وال 4 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('4997', 'STAR LAVABLE ECOWALL 10KG (ستار لافابل إيكو وال 10 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('5505', 'SECAM FIXATEUR A EAU 4.5KG (سيكام فيكساتور ماء 4.5 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('9232', 'SECAM FIXATEUR A EAU 10KG (سيكام فيكساتور ماء 10 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('5574', 'SECAM FIXATEUR A HUILE 4L (سيكام فيكساتور زيت 4 لتر)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('5575', 'SECAM FIXATEUR A HUILE 20KG (سيكام فيكساتور زيت 20 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('10250', 'VALPAINT FIXATEUR FIX FOND 18KG (فالبانت فيكساتور فيكس فون 18 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('SPRINT 32', 'PROFINICH ENDUIT PATE M01 (بروفينش لاندوي باط أم 01)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('SPRINT 30W', 'PROFINICH ENDUIT PATE M02 (بروفينش لاندوي باط أم 02)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('AIGKE 27', 'MEGA ENDUIT 20KG PATE (ميغا لاندوي باط 20 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('3105', 'MEGA ENDUIT PATE 10KG (ميغا لاندوي باط 10 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('5967', 'MEGA ENDUIT PATE 05KG (ميغا لاندوي باط 5 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('10647', 'MIDY ENDUIT PATE 300 20KG (ميدي لاندوي باط 20 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('4963', 'MIDY ENDUIT PATE 5KG (ميدي لاندوي باط 5 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('SPRINT 45', 'PIGMA ENDUIT PATE 10KG (بيغما لاندوي باط 10 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('5462', 'RAYAN ENDUIT S/P FINITION 20KG (ريان لاندوي فينيسيون 20 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('MAUR3', 'VALPAINT SATINE BASE A 18KG (فالبانت ساتيني باز أ 18 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('5504', 'SECAM SATINE 05KG (سيكام ساتيني 5 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('5250', 'SECAM SATINE 10KG (سيكام ساتيني 10 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('2461', 'SECAM SATINE 18KG (سيكام ساتيني 18 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('PIGMA-LAQ-18', 'PIGMA LAQUE BLANC 18KG (بيغما لاك أبيض 18 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('4711', 'MEGA SABLE DOR 4KG (ميغا صابلي ذهبي 4 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('2288', 'MEGA SABLE ORO 4KG (ميغا صابلي ذهبي أورو 4 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('2794', 'MEGA SABLE 04KG BLANC (ميغا صابلي أبيض 4 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('3543', 'PIGMA SABLE BLANC 5KG (بيغما صابلي أبيض 5 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('8606', 'PROFINICH ARENA DORE 3KG (بروفينش أرينا ذهبي 3 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('8532', 'SKY COLOR GALAXY 01 DORE (سكاي كولور قالاكسي 01 ذهبي)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('PU?NC', 'SKY COLOR GALAXY 02 ARGENT (سكاي كولور قالاكسي 02 فضي)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('8531', 'SKY COLOR GALAXY 04 ROUGE (سكاي كولور قالاكسي 04 أحمر)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('10155', 'SKY COLOR GALAXY 07 GRIS ARGENT NOIR (سكاي كولور قالاكسي 07 رمادي فضي أسود)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('SKY-GAL-08', 'SKY COLOR GALAXY 08 DORE ARGENT BRONZE (سكاي كولور قالاكسي 08 ذهبي فضي برونز)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('SKY-GAL-09', 'SKY COLOR GALAXY 09 ROUGE DORE ARGENT (سكاي كولور قالاكسي 09 أحمر ذهبي فضي)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('8463', 'SKY COLOR GALAXY 010 DORRE ARGENT MARRON (سكاي كولور قالاكسي 010 ذهبي فضي بني)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('FOUR 1R', 'SKY COLOR GALAXY 011 DORE ROUGE (سكاي كولور قالاكسي 011 ذهبي أحمر)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('10233', 'SKY COLOR GALAXY 015 ARGENT DORE NOIR (سكاي كولور قالاكسي 015 فضي ذهبي أسود)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('SKY-GAL-016', 'SKY COLOR GALAXY 016 ARGENT NOIR MARRON (سكاي كولور قالاكسي 016 فضي أسود بني)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('SKY-GAL-017', 'SKY COLOR GALAXY 017 BRONZE ARGENT MARRON (سكاي كولور قالاكسي 017 برونز فضي بني)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('SKY-GAL-018', 'SKY COLOR GALAXY 018 MAUVE DORE ARGENT (سكاي كولور قالاكسي 018 موف ذهبي فضي)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('SKY-GAL-022', 'SKY COLOR GALAXY 022 ROSE ARGENT (سكاي كولور قالاكسي 022 وردي فضي)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('8482', 'SKY COLOR GALAXY 023 NOIR ARGENT MARRON DORE (سكاي كولور قالاكسي 023 أسود فضي بني ذهبي)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('8483', 'SKY COLOR GALAXY 024 DORE BRONZE NOIR (سكاي كولور قالاكسي 024 ذهبي برونز أسود)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('8487', 'SKY COLOR GALAXY 027 BRONZE (سكاي كولور قالاكسي 027 برونز)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('SKY-GAL-033', 'SKY COLOR GALAXY 033 BRONZE NOIR (سكاي كولور قالاكسي 033 برونز أسود)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('BAG-MO-25', 'BAGUETTE MOULEUR MO 25 (باغيت مولور 25)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Placo & Décoration PVC'),
  ('BAG-MO-40', 'BAGUETTE MOULEUR MO 40-178 (باغيت مولور 40)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Placo & Décoration PVC'),
  ('2286', 'BAGUETTE DECORE DOREE PM 2CM (باغيت ديكور ذهبي صغير 2سم)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Placo & Décoration PVC'),
  ('9837', 'BAGUETTE DECORE DOREE 3CM (باغيت ديكور ذهبي 3سم)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Placo & Décoration PVC'),
  ('11141', 'BAGUETTE DECORE CHROMI PM (باغيت ديكور كرومي صغير)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Placo & Décoration PVC'),
  ('11134', 'BAGUETTE DECORE CHROMI GM (باغيت ديكور كرومي كبير)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Placo & Décoration PVC'),
  ('GANTS-PROT', 'GANTS DE PROTECTION CHANTIER (قونتيات حماية للعمل)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('RECH-MINI-ROUL', 'RECHARGE MINI ROULEAUX 10PCS (روشارج ميني رولو 10 قطع)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('PINC-RAD-40', 'PINCEAU RADIATEUR N°40 (باندا بانسو كودي 40)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('PINC-RAD-50', 'PINCEAU RADIATEUR N°50 (باندا بانسو كودي 50)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('ROUL-CANICHE-29', 'ROULEAU CANICHE RAVALEMENT 29 (رولو كانيش رافالمان 29)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('PLATOIR-TRANSP', 'PLATOIR TRANSPARENT DECOR (بلاطوار شفاف ديكور)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('5514', 'PANDA LISSEUSE ENDUIT 40CM (باندا ليسوز لاندوي 40 سم)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('5515', 'PANDA LISSEUSE ENDUIT 60CM (باندا ليسوز لاندوي 60 سم)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('9323', 'MIDY LAQUE MARRON DATTE 700G (ميدي لاك بني تمر 700 غ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('9648', 'MIDY LAQUE MARRON DATTE 2.7KG (ميدي لاك بني تمر 2.7 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('1305', 'MIDY LAQUE MARRON FONCE 2.7KG (ميدي لاك بني غامق 2.7 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('9806', 'MEGA LAVABLE 7KG ROUGE BRIQUE GP62 (ميغا لافابل 7 كغ أحمر بريك)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('9747', 'MEGA LAVABLE 7KG ROSE FONCE GP67 (ميغا لافابل 7 كغ وردي غامق)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('9746', 'MEGA LAVABLE 7KG ROSE CLAIR GP70 (ميغا لافابل 7 كغ وردي فاتح)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('9269', 'MEGA LAVABLE 7KG MARRON GP180 (ميغا لافابل 7 كغ بني)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('9270', 'MEGA LAVABLE 7KG GRIS CLAIR GP79 (ميغا لافابل 7 كغ رمادي فاتح)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('2364', 'MEGA LAVABLE 7KG CAPPUCCINO GP340 (ميغا لافابل 7 كغ كابوتشينو)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('80Y', 'MEGA LAVABLE 7KG BLEU GP23 (ميغا لافابل 7 كغ أزرق)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('AIGLE 62', 'MEGA LAVABLE 7KG CREME GP310 (ميغا لافابل 7 كغ كريمي)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('PMD', 'MEGA LAVABLE 7KG BEIGE GP201 (ميغا لافابل 7 كغ بيج)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('5793', 'MEGA LAVABLE ECO MAX 25KG (ميغا لافابل إيكو ماكس 25 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('2252', 'ESSAADA LAVABLE 20KG JUNIOR (السعادة لافابل 20 كغ جونيور)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('9953', 'ESSAADA LAVABLE 25KG CLASSIC (السعادة لافابل 25 كغ كلاسيك)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('4976', 'ESSAADA LAVABLE 4KG JUNIOR (السعادة لافابل 4 كغ جونيور)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('3554', 'ESSAADA LAVABLE 10KG JUNIOR (السعادة لافابل 10 كغ جونيور)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('836', 'ESSAADA MASTIC FER 700GR (السعادة ماستيك حديد 700 غ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Droguerie & Mastics'),
  ('5274', 'COLLE SILICONE PARE-BRISE AB (كول سيليكون باربريز أ ب)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Droguerie & Mastics'),
  ('2147', 'COLLE SILICONE RS BLANC 280ML (كول سيليكون أبيض 280 مل)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Droguerie & Mastics'),
  ('1550', 'COLLE SILICONE FIXCOL NOIR (كول سيليكون فيكسكول أسود)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Droguerie & Mastics'),
  ('3126', 'SNIC LAVABLE VINYROC 25KG (سنيك لافابل فينيروك 25 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('10565', 'SNIC LAVABLE 25KG PLASTIC (سنيك لافابل 25 كغ بلاستيك)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('A4APOD', 'SNIC LAVABLE 20KG (سنيك لافابل 20 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('045', 'SNIC LAVABLE 10KG (سنيك لافابل 10 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('2061', 'SNIC LAVABLE 5KG (سنيك لافابل 5 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('4482', 'MINIROS MINI ROULEAU MICROFIBRE 10-6 (مينيروس ميني رولو ميكروفيبر)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('2238', 'LE LUX ROULEAU LAQUE PM (لو لوكس رولو لاك صغير)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('PMPJS', 'MINIROS ROULEAU SATINE AGMP20 (مينيروس رولو ساتيني)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('7800', 'PANDA ROULEAU ENDUIT (باندا رولو لاندوي)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('5852', 'PANDA ROULEAU ENDUIT 10 CM (باندا رولو لاندوي 10 سم)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('4866', 'PIGMA CIMENT COLLE BLANC 25KG (بيغما سيما كول أبيض 25 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('APPARDD', 'PUMA CE BLANC 591 25KG (بوما أبيض 25 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('5405', 'LA FARGE PATE A JOINT BEIGE 5KG (لافارج باط أ جوان بيج 5 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('5409', 'LA FARGE PATE A JOINT GRIS CLAIR 5KG (لافارج باط أ جوان رمادي فاتح 5 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('5404', 'LA FARGE PATE A JOINT NOIR 5KG (لافارج باط أ جوان أسود 5 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Peinture & Enduits'),
  ('1858', 'MONTRE DECORATIVE MURALE 80CM (ساعة حائط ديكور 80 سم)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Placo & Décoration PVC'),
  ('18384', 'SPOT SAMSUNG 24W 3D (سبوت سامسونغ 24 واط)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('LMP-W15W', 'LAMPE 15W WELLMAX (لامبة 15 واط ويلماكس)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('LMP-WELLMAX', 'LAMPE 18W LED WELLMAX (لامبة 18 واط ليد ويلماكس)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('13310', 'LAMPE 7W WELLMAX (لامبة 7 واط ويلماكس)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('13311', 'LAMPE 9W LED WELLMAX (لامبة 9 واط ليد ويلماكس)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('21228', 'LAMPE 40W LED WELLMAX (لامبة 40 واط ليد ويلماكس)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('21227', 'LAMPE 50W LED WELLMAX (لامبة 50 واط ليد ويلماكس)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('22659', 'LAMPE 60W LED WELLMAX (لامبة 60 واط ليد ويلماكس)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('21225', 'LAMPE 30W LED WELLMAX HAMMER (لامبة 30 واط ويلماكس هامر)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('FTNX-10WT', 'SPOT FOTONIX 3D 10WT (سبوت فوتونيكس 10 واط)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('16844', 'SPOT FOTONIX 3D 18WT (سبوت فوتونيكس 18 واط)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('FTNX-3D-24W', 'SPOT FOTONIX 3D 24WT (سبوت فوتونيكس 24 واط)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('FTNX-3D-36W', 'SPOT FOTONIX 3D 36WT (سبوت فوتونيكس 36 واط)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('SPT-10W-3D', 'SPOT 10W 3D MOONMAX (سبوت 10 واط مونماكس)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('14988', 'SPOT 18W 3D MOONMAX (سبوت 18 واط مونماكس)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('1924', 'FIL MEPLAT 2X2.5 100M EL WAFAA (خيط مبلا 2*2.5 / 100م الوفاء)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('00830', 'JEUX DE LUMIERE 100M FOMSI RGB (حبل ضوء 100م ملون فومسي)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('4859', 'JEUX DE LUMIERE 100M FOMSI BLANC (حبل ضوء 100م أبيض فومسي)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('LA065WW', 'JEUX DE LUMIERE 100M FOMSI JAUNE (حبل ضوء 100م أصفر فومسي)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('11048', 'LAMPE 9W SAMSUNG RECHARGEABLE (لامبة 9 واط سامسونغ روشارجابل)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('MCC006', 'CONTINUUME BOUTON POUSSOIR (كونتينيو بوطون بوسوار)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('C001', 'CONTINUUME INTERRUPTEUR SIMPLE (كونتينيو أنتربتور سامبل)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('C119', 'CONTINUUME FICHE F (كونتينيو فيش ف)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('C003', 'CONTINUUME INTERRUPTEUR DOUBLE (كونتينيو أنتربتور دوبل)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('C014', 'CONTINUUME PRISE SIMPLE (كونتينيو بريز سامبل)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('C015', 'CONTINUUME PRISE DE TERRE (كونتينيو بريز تير)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('SASKBO', 'SKY BOUTON POUSSOIR (سكاي بوطون بوسوار)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('SASKPT', 'SKY PRISE TERRE (سكاي بريز تير)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('SASKPSAT', 'SKY SATELLITE FICHE F (سكاي فيش ساتيليت)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('SASKC2H', 'SKY CADRE DOUBLE BLANC (سكاي كادر دوبل أبيض)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('KBS001', 'BMS KARREA INTERRUPTEUR SIMPLE (بي أم أس كاري أنتربتور سامبل)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('KBS014', 'BMS KARREA PRISE SIMPLE (بي أم أس كاري بريز سامبل)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('KBS119', 'BMS KARREA SATELLITE F (بي أم أس كاري ساتيليت ف)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('KBS010', 'BMS KARREA VA ET VIENT (بي أم أس كاري فافيانت)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('KBS003', 'BMS KARREA DOUBLE ALLUMAGE (بي أم أس كاري دوبل ألوماج)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('KBS006', 'BMS KARREA BOUTON POUSSOIR (بي أم أس كاري بوطون بوسوار)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('KBS015', 'BMS KARREA PRISE AVEC TERRE (بي أم أس كاري بريز تير)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('KBS020', 'BMS KARREA PRISE DOUBLE (بي أم أس كاري بريز دوبل)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('KBS092V', 'BMS MODULE DOUBLE NOIR VERTICAL (بي أم أس كادر دوبل أسود عمودي)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('KBS093V', 'BMS MODULE TRIPLE NOIR VERTICAL (بي أم أس كادر تريبل أسود عمودي)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('KBS094V', 'BMS MODULE 4 NOIR VERTICAL (بي أم أس كادر 4 أسود عمودي)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('D003C', 'BOITE ENCASTREMENT CARRE BMS (بواطة أنكاسترومون كاري بي أم أس)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('12398', 'BOITE ENCASTREMENT CARRE 10PCS (بواطة أنكاسترومون كاري 10 قطع)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('D003', 'BOITE ENCASTREMENT BMS 50PCS (بواطة أنكاسترومون بي أم أس 50 قطعة)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('8864', 'BOITE ENCASTREMENT 150PCS (بواطة أنكاسترومون 150 قطعة)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('SASOISA', 'SOUKOY INTERRUPTEUR SIMPLE (سوكوي أنتربتور سامبل)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('SASOPS', 'SOUKOYE PRISE SIMPLE (سوكوي بريز سامبل)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('SASOPT', 'SOUKOYE PRISE AVEC TERRE (سوكوي بريز تير)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('SASODP', 'SOUKOY DOUBLE PRISE SIMPLE (سوكوي دوبل بريز)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('SAVOPS', 'VORTEX PRISE SIMPLE (فورتكس بريز سامبل)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('SAVOPTR', 'VORTEX PRISE AVEC TERRE (فورتكس بريز تير)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('SAVOISA', 'VORTEX INTERRUPTEUR SIMPLE (فورتكس أنتربتور سامبل)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('22768', 'HUBLOT MIYASSE BLANC (أوبلو مياس أبيض)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('22769', 'HUBLOT MIYASSE NOIRE (أوبلو مياس أسود)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('22770', 'HUBLOT AMINE BLANC (أوبلو أمين أبيض)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('22771', 'HUBLOT AMINE NOIRE (أوبلو أمين أسود)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('1800', 'HUBLOT SAMSUNG 18W ROND DETECTEUR (أوبلو سامسونغ 18 واط مدور ديتكتور)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('22788', 'HUBLOT MURAL ETANCHE 004 (أوبلو جداري إيتونش 004)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('22787', 'HUBLOT MURAL ETANCHE 002 (أوبلو جداري إيتونش 002)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('FEV13', 'BMS BOITE DEPART 13P AVEC VOYANT (بواطة ديبار 13 بي أم أس)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('FEV10', 'BMS BOITE DEPART 10P AVEC VOYANT (بواطة ديبار 10 بي أم أس)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('TDE-18D', 'MONO BOITE DEPART ENCASTRE 18/2 ETAGES (بواطة ديبار مونو 18)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('TDE-12D', 'MONO BOITE DEPART ENCASTRE 12 (بواطة ديبار مونو 12)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('TDE-16D', 'MONO BOITE DEPART ENCASTRE 16 (بواطة ديبار مونو 16)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('TDE-08D', 'MONO BOITE DEPART ENCASTRE 08 (بواطة ديبار مونو 8)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('TDE-24D', 'MONO BOITE DEPART ENCASTRE 24 (بواطة ديبار مونو 24)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('TDEN-16D', 'MONO BOITE DEPART ENCASTRE NOIR 16D (بواطة ديبار مونو سوداء 16)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('TDEN-24D', 'MONO BOITE DEPART ENCASTRE NOIR 24D (بواطة ديبار مونو سوداء 24)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('TDEN-12D', 'MONO BOITE DEPART ENCASTRE NOIR 12D (بواطة ديبار مونو سوداء 12)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('TDEN-36D', 'MONO BOITE DEPART ENCASTRE NOIR 36D (بواطة ديبار مونو سوداء 36)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('TDE-36D', 'MONO BOITE DEPART ENCASTRE 36 (بواطة ديبار مونو 36)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('JDDD', 'FLOLIGHT BOITE DEPART 36P ENCASTRE (فلو لايت بواطة ديبار 36)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('SBE24N', 'SOUKOY BOITE DEPART 24D ENCASTRE NOIR (سوكوي بواطة ديبار 24 سوداء)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('SBE16N', 'SOUKOY BOITE DEPART 16D ENCASTRE NOIR (سوكوي بواطة ديبار 16 سوداء)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('FA02', 'BOITE DEPART 02 POLES BMS (بواطة ديبار 2 بول بي أم أس)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('MD1-16A', 'UNIPOLAIRE BMS 16A MD (ديجونكتور أوني بولير 16 أمبير بي أم أس)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('MD1-25A', 'UNIPOLAIRE BMS 25A MD (ديجونكتور أوني بولير 25 أمبير بي أم أس)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('MD1-10A', 'UNIPOLAIRE BMS 10A MD (ديجونكتور أوني بولير 10 أمبير بي أم أس)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('MD1-20A', 'UNIPOLAIRE BMS 20A MD (ديجونكتور أوني بولير 20 أمبير بي أم أس)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('DPN-10A', 'UNIPOLAIRE BMS 10A PH+N (ديجونكتور 10 أمبير فاز ونوتر بي أم أس)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('DPN-16A', 'UNIPOLAIRE BMS 16A PH+N (ديجونكتور 16 أمبير فاز ونوتر بي أم أس)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('DPN-20A', 'UNIPOLAIRE BMS 20A PH+N (ديجونكتور 20 أمبير فاز ونوتر بي أم أس)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('DPN-25A', 'UNIPOLAIRE BMS 25A PH+N (ديجونكتور 25 أمبير فاز ونوتر بي أم أس)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('12219-1', 'PROTECTEUR DE TENSION YSMAX 40A/220V (بروتكتور حماية يسماكس 40 أمبير)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('22480', 'PROTECTEUR DE TENSION YSMAX 60A/220V (بروتكتور حماية يسماكس 60 أمبير)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('TDA-04D', 'MONO BOITE DEPART 04 POLES (بواطة ديبار مونو 4 بول)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('DB-2P45A', 'BMS DISJONCTEUR 220V / 45A (ديجونكتور بي أم أس 220ف / 45 أمبير)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('DB-2P32A', 'BMS DISJONCTEUR 220V / 32A (ديجونكتور بي أم أس 220ف / 32 أمبير)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('DB-4P63A', 'BMS DISJONCTEUR 380V / 63A (ديجونكتور بي أم أس 380ف / 63 أمبير)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('DB-4P45A', 'BMS DISJONCTEUR 380V / 45A (ديجونكتور بي أم أس 380ف / 45 أمبير)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('BDD2-2P40A30', 'BMS DISJONCTEUR DIFFERENTIEL 2P 40A 300MA (ديجونكتور ديفيرونسييل بي أم أس)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('GAINE-16-MOH', 'GAINE GORGE N°16 MOH (غين كرجوجة 16)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('GAINE-20-MOH', 'GAINE GORGE N°20 MOH (غين كرجوجة 20)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('GAINE-25-MOH', 'GAINE GORGE N°25 MOH 50M (غين كرجوجة 25)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('GAINE-32-MOH', 'GAINE GORGE N°32 MOH 50M (غين كرجوجة 32)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('16286', 'CABLE SOUPLE 2X0.75 CASTELUM (كابل سوبل 2*0.75 كاستلوم)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('13195', 'PELLE A SUCRE PLASTIC GM (بالة سكر بلاستيك كبيرة)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('19439', 'APPLIQUE ISILDAR 7155 POTEAU (أبليك بوتو إيسيلدار)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('15225', 'COLLE SUPER GLUE + DURCISSEUR FINK 100ML (سوبر قلو مع دورسيسور فينك 100 مل)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Droguerie & Mastics'),
  ('22476', 'COLLE SUPER GLUE + DURCISSEUR FINEK 200ML (سوبر قلو مع دورسيسور فينك 200 مل)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Droguerie & Mastics'),
  ('20434', 'COLLE SUPER GLUE + DURCISSEUR POLIER FIX 400ML (سوبر قلو مع دورسيسور بوليير فيكس 400 مل)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Droguerie & Mastics'),
  ('21710', 'COLLE SUPER GLUE INCON 12PCS (سوبر قلو أنكون 12 حبة)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Droguerie & Mastics'),
  ('ORP-031', 'MONO MULTIPRISE ORION 3P 1.5M (ملتيباريز مونو أوريون 3 مقابس 1.5م)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('ORP-033', 'MONO MULTIPRISE ORION 3P 3M (ملتيباريز مونو أوريون 3 مقابس 3م)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Électricité & Éclairage'),
  ('9349-4', 'PISTOLET SILICONE ABC (بيستولي سيليكون أ ب س)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('OM-LD', 'RABOT PLACO BA13 PM (رابو بلاكو صغير)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('5625', 'RABOT PLACO BA13 GM (رابو بلاكو كبير)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('140109', 'PISTOLET SILICONE NWSD (بيستولي سيليكون)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('20475', 'CUTTER PLIANT ENCONI (كيتور مطوي أنكوني)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('10031-12', 'SCIE ALIKO KAKU N°6 (منشار أليكو كاكو 6)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('1521', 'CORDAX + NIVEAU A BULLE (كورداكس + نيفو)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('8683', 'CORDAX FIX TOPE (كورداكس فيكس طوب)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('12729', 'CUTTER JEU DE 3 PCS (كيتور طاقم 3 حبات)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('12108-3', 'CUTTER PM 12PCS (كيتور صغير 12 حبة)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('15735', 'METRE RUBAN 3M FACOME (متر 3م فاكوم)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('EMTP3316M', 'METRE RUBAN 3M EMTOP 16MM (متر 3م إمتوب 16مم)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('DTMT1230M', 'DYLLU METRE RUBAN 5M*25MM (متر 5م ديلو)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('4061', 'METRE RUBAN 5M FACOME LUX 25MM (متر 5م فاكوم لوكس)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('51004DING', 'METRE RUBAN 5M DING 25MM (متر 5م دينغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('DTHM1301', 'DYLLU MARTEAU 100G (مطرقة ديلو 100غ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('22730', 'MARTEAU ARRACHE CLOU HD PLASTIC (مطرقة كلاليب بلاستيك)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('11573', 'RECHANGE DE CUTTER MOUSTACHE (لام كيتور موستاش)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('18685', 'TRINGLE ADEL DOUBLE BLANC (ترانغل عادل دوبل أبيض)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('18688', 'TRINGLE ADEL DOUBLE BRONZE (ترانغل عادل دوبل برونز)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('18416', 'TRINGLE ADEL DOUBLE NOIR (ترانغل عادل دوبل أسود)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('18684', 'TRINGLE ADEL SIMPLE BLANC (ترانغل عادل سامبل أبيض)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('18413', 'TRINGLE ADEL SIMPLE NOIR (ترانغل عادل سامبل أسود)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('18412', 'TRINGLE ADEL/ASTA SIMPLE BRONZE (ترانغل عادل سامبل برونز)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('18686', 'TRINGLE ADEL/ASTA SIMPLE CHROME (ترانغل عادل سامبل كرومي)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('18410', 'TRINGLE ADEL/ASTA SIMPLE CUIVRE (ترانغل عادل سامبل نحاسي)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('15397', 'DISQUE INOX 115MM WANLON (ديسك إينوكس 115مم وانلون)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('EACD121155', 'DISQUE INOX EMTOP 115*1.2 10PCS (ديسك إينوكس إمتوب 115مم)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('CTDDP0001', 'DISQUE DIAMANT 115 CROWN VERT (ديسك ديامون كراون 115 أخضر)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('DTDC4K05', 'DYLLU DISQUE DIAMANT 230 ULTRA FIN (ديسك ديامون ديلو 230 ألترا فان)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('12983', 'DISQUE RESINE SCRATCH 115 N°100 (ديسك ريزين سكراش 115 رقم 100)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('12984', 'DISQUE RESINE SCRATCH 115 N°60 (ديسك ريزين سكراش 115 رقم 60)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('ECIDL20668', 'VISSEUSE EMTOP 20V (فيسوز إمتوب 20ف)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('ECDL12456', 'VISSEUSE EMTOP 12V (فيسوز إمتوب 12ف)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('ECSR0408', 'VISSEUSE EMTOP 4V (فيسوز إمتوب 4ف)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('DTCV4401', 'DYLLU VISSEUSE 4V (فيسوز ديلو 4ف)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('DTCDS510', 'DYLLU VISSEUSE 12V (فيسوز ديلو 12ف)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('ECIDL20968', 'VISSEUSE EMTOP 20V 4A (فيسوز إمتوب 20ف 4أمبير)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('DTED15401', 'DYLLU PERCEUSE 400W (بيرسوز ديلو 400 واط)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('DTED15501', 'DYLLU PERCEUSE 500W (بيرسوز ديلو 500 واط)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('CT13668', 'PONCEUSE CROWN 180MM (بونسوز كراون 180مم)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('5351', 'MARTEAU PIQUEUR SOFICLEF MP1050-26 (بيكور صوفيكليف 1050 واط)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('RH1500-32', 'MARTEAU PIQUEUR SOFICLEF 32MM 1500W (بيكور صوفيكليف 1500 واط)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('MP800K', 'MARTEAU PIQUEUR SOFICLEF 26MM 800W MP800K (بيكور صوفيكليف 800 واط)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('BURI', 'MARTEAU PIQUEUR FIX TOP 850W (بيكور فيكس طوب 850 واط)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('HILTI-6-110', 'MECHE HILTI N°6/110 (ميش هيلتي 6/110)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('HILTI-8-110', 'MECHE HILTI N°8/110 (ميش هيلتي 8/110)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('HILTI-10', 'MECHE HILTI N°10 (ميش هيلتي 10)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('14254', 'MECHE SL N°6 (ميش 6)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('14250', 'MECHE SL N°4 (ميش 4)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('ETDB10401', 'MECHE ACIER HSS N°4 EMTOP (ميش حديد إمتوب 4)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('ETDB10501', 'MECHE ACIER HSS N°5 EMTOP (ميش حديد إمتوب 5)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('ETDB10601', 'MECHE ACIER HSS N°6 EMTOP (ميش حديد إمتوب 6)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('MCH-HSS-07', 'MECHE ACIER HSS N°7 SL (ميش حديد 7)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('9326-4', 'EMBOUT TOURNEVIS 10PCS CHROME (أمبو كرومي 10 قطع)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('9987', 'EMBOUT CROWN N°13 (أمبو كراون 13)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('ESBTMPH233', 'EMBOUT TOURNEVIS JEUX 10PCS EMTOP (أمبو طاقم 10 قطع إمتوب)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('12275', 'EMBOUT N°10 5PCS (أمبو 10 طاقم 5 قطع)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('12274', 'EMBOUT N°13 5PCS (أمبو 13 طاقم 5 قطع)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('20748', 'ESCABEAU ALLUM SAF LEDER N°4 (سلم ألمنيوم 4 درجات)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('10986', 'ESCABEAU ALLUM N°05 SCALE VALENCIA (سلم ألمنيوم فالنسيا 5 درجات)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('TASILI-E40KG', 'BALANCE ELECTRONIQUE TASSILI 40KG (ميزان إلكتروني طاسيلي 40 كغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('DTLE2M03', 'DYLLU NIVEAU LASER AUTO 30M L/VERT (نيفو ليزر ديلو 30م أخضر)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('DTLE8M12', 'DYLLU NIVEAU LASER 3D/360° (نيفو ليزر ديلو 360 درجة)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('ESLE2M05', 'NIVEAU LASER EMTOP 5 LIGNES (نيفو ليزر إمتوب 5 خطوط)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('12113-14', 'SERRE JOINT N°40 VAST KING (سير جوان 40 فاست كينغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('12114-1', 'SERRE JOINT N°60 VAST KING (سير جوان 60 فاست كينغ)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('515', 'SCIE A CLOCHE 16PCS OPTIMUS (منشار ثقب 16 قطعة أوبتيموس)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('DTHX1630', 'DYLLU CORDAX + NIVEAU 30M (كورداكس + نيفو ديلو 30م)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('16938', 'COLLIER MULTICOUCHE 16 SPHAX (كولي مالتيكوش 16)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Placo'),
  ('CH13003', 'CHARBON CROWN 115 OR / 1601 CT13003 (شاربون كراون 115)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('CH10085', 'CHARBON CROWN PERC 13MM 500W (شاربون كراون بيرسوز)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('2169', 'CHARBON BOSCH 230MM BS180 (شاربون بوش 230مم)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('CHARBONE', 'CHARBON JEUX 12PCS SL (طاقم شاربون 12 قطعة)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('CH18021', 'CHARBON CROWN J45/1700 -18024/ 18021 (شاربون كراون)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('CH10077', 'CHARBON CROWN OR 13M CT100/77 (شاربون كراون 13)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage'),
  ('CH18056', 'CHARBON MARTEAU PIQUEUR 32MM 18056 (شاربون بيكور 32مم)', 0::numeric, 0::numeric, 0::numeric, 0::integer, 5::integer, 'Quincaillerie & Outillage')
) AS v(sku, name, price, wholesale_price, special_price, stock, min_stock, category)
LIMIT 528;

-- 3. Diagnostic check (returns the number of inserted products)
SELECT count(*) AS total_products_in_database FROM public.products;
